-- Run this file once in the Supabase SQL Editor.

create table if not exists public.customer_logs (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  old_status text,
  new_status text,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists customer_logs_customer_created_idx
  on public.customer_logs (customer_id, created_at desc);

alter table public.customer_logs enable row level security;

drop policy if exists "Authenticated users read customer logs" on public.customer_logs;
create policy "Authenticated users read customer logs"
  on public.customer_logs for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users insert customer logs" on public.customer_logs;
create policy "Authenticated users insert customer logs"
  on public.customer_logs for insert
  to authenticated
  with check (true);
