-- Run once in Supabase SQL Editor before enabling Jettel call sync/webhooks.
-- Extends the existing call_sessions table without storing Jettel API secrets.

alter table public.call_sessions
  add column if not exists provider text not null default 'microsip',
  add column if not exists external_call_id text,
  add column if not exists call_uuid text,
  add column if not exists caller_name text,
  add column if not exists extension text,
  add column if not exists transfer_target text,
  add column if not exists recording_url text,
  add column if not exists recording_storage_path text,
  add column if not exists recording_fetched_at timestamptz,
  add column if not exists recording_error text,
  add column if not exists waiting_seconds integer,
  add column if not exists raw_event jsonb not null default '{}'::jsonb;

create index if not exists call_sessions_provider_external_idx
  on public.call_sessions (provider, external_call_id)
  where external_call_id is not null;

create index if not exists call_sessions_provider_uuid_idx
  on public.call_sessions (provider, call_uuid)
  where call_uuid is not null;

create index if not exists call_sessions_phone_created_idx
  on public.call_sessions (phone, created_at desc);

create index if not exists call_sessions_recording_created_idx
  on public.call_sessions (created_at desc)
  where recording_url is not null;

create table if not exists public.jettel_extensions (
  extension text primary key,
  ext_id text,
  profile_id uuid references public.profiles(id) on delete set null,
  display_name text,
  line_number text,
  group_name text,
  is_active boolean not null default true,
  is_connected boolean not null default false,
  last_seen_at timestamptz,
  raw_status jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.jettel_extensions
  add column if not exists ext_id text,
  add column if not exists profile_id uuid references public.profiles(id) on delete set null,
  add column if not exists display_name text,
  add column if not exists line_number text,
  add column if not exists group_name text,
  add column if not exists is_active boolean not null default true,
  add column if not exists is_connected boolean not null default false,
  add column if not exists last_seen_at timestamptz,
  add column if not exists raw_status jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists jettel_extensions_profile_idx
  on public.jettel_extensions (profile_id)
  where profile_id is not null;

create index if not exists jettel_extensions_ext_id_idx
  on public.jettel_extensions (ext_id)
  where ext_id is not null;

alter table public.jettel_extensions enable row level security;

drop policy if exists "jettel_extensions_select_by_role" on public.jettel_extensions;
create policy "jettel_extensions_select_by_role"
on public.jettel_extensions
for select
to authenticated
using ((select public.current_user_customer_role()) in ('boss', 'manager'));

drop policy if exists "jettel_extensions_write_by_boss" on public.jettel_extensions;
create policy "jettel_extensions_write_by_boss"
on public.jettel_extensions
for all
to authenticated
using ((select public.current_user_customer_role()) = 'boss')
with check ((select public.current_user_customer_role()) = 'boss');

create table if not exists public.jettel_action_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_extension text,
  target_phone text,
  status text not null check (status in ('success', 'failed')),
  provider_code text,
  provider_message text,
  raw_request jsonb not null default '{}'::jsonb,
  raw_response jsonb not null default '{}'::jsonb,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists jettel_action_logs_created_idx
  on public.jettel_action_logs (created_at desc);

create index if not exists jettel_action_logs_user_created_idx
  on public.jettel_action_logs (user_id, created_at desc)
  where user_id is not null;

alter table public.jettel_action_logs enable row level security;

drop policy if exists "jettel_action_logs_select_by_role" on public.jettel_action_logs;
create policy "jettel_action_logs_select_by_role"
on public.jettel_action_logs
for select
to authenticated
using (
  (select public.current_user_customer_role()) in ('boss', 'manager')
  or user_id = (select auth.uid())
);

revoke insert, update, delete on table public.jettel_action_logs from authenticated;
grant select on table public.jettel_action_logs to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'jettel_action_logs'
  ) then
    alter publication supabase_realtime add table public.jettel_action_logs;
  end if;
end
$$;

insert into public.jettel_extensions (extension, ext_id, display_name, line_number, group_name)
values
  ('101', '101-pbx349', '101', '902129030222', 'Default'),
  ('102', '102-pbx349', '102', '902129030222', 'Default'),
  ('103', '103-pbx349', '103', '902129030222', 'Default'),
  ('104', '104-pbx349', '104', '902129030222', 'Default'),
  ('105', '105-pbx349', '105', '902129030222', 'Default'),
  ('106', '106-pbx349', '106', '902129030222', 'Default'),
  ('107', '107-pbx349', '107', '902129030222', 'Default'),
  ('108', '108-pbx349', '108', '902129030222', 'Default'),
  ('109', '109-pbx349', '109', '902129030222', 'Default'),
  ('110', '110-pbx349', '110', '902129030222', 'Default')
on conflict (extension) do update
set ext_id = coalesce(public.jettel_extensions.ext_id, excluded.ext_id),
    display_name = excluded.display_name,
    line_number = excluded.line_number,
    group_name = excluded.group_name,
    updated_at = now();

grant select, update on table public.jettel_extensions to authenticated;

notify pgrst, 'reload schema';
