-- Run this file once in the Supabase SQL Editor.

create table if not exists public.user_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 5000),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists user_notes_user_created_idx
  on public.user_notes (user_id, created_at desc);

alter table public.user_notes enable row level security;

drop policy if exists "Users manage own notes" on public.user_notes;
create policy "Users manage own notes"
  on public.user_notes
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

grant select, insert, update, delete on table public.user_notes to authenticated;
