-- Run this file once in the Supabase SQL Editor.

alter table public.profiles
  add column if not exists avatar_url text,
  add column if not exists job_title text,
  add column if not exists phone text,
  add column if not exists bio text,
  add column if not exists availability_status text not null default 'online'
    check (availability_status in ('online', 'busy')),
  add column if not exists updated_at timestamptz default now();

alter table public.profiles enable row level security;

drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile"
  on public.profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

grant select on table public.profiles to authenticated;

drop policy if exists "Authenticated users view office profiles" on public.profiles;
create policy "Authenticated users view office profiles"
  on public.profiles for select
  to authenticated
  using (true);

create table if not exists public.app_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 2000),
  attachment_url text,
  attachment_name text,
  attachment_type text,
  reply_to_id bigint references public.app_messages(id) on delete set null,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  edited_at timestamptz
);

create index if not exists app_messages_created_idx
  on public.app_messages (created_at desc);

create index if not exists app_messages_sender_recipient_idx
  on public.app_messages (sender_id, recipient_id, created_at desc);

alter table public.app_messages enable row level security;

drop policy if exists "Authenticated users read relevant messages" on public.app_messages;
create policy "Authenticated users read relevant messages"
  on public.app_messages for select
  to authenticated
  using (
    recipient_id is null
    or sender_id = auth.uid()
    or recipient_id = auth.uid()
  );

drop policy if exists "Authenticated users send messages" on public.app_messages;
create policy "Authenticated users send messages"
  on public.app_messages for insert
  to authenticated
  with check (
    sender_id = auth.uid()
    and (recipient_id is null or recipient_id <> auth.uid())
  );

create or replace function public.mark_messages_read(p_sender_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update public.app_messages
  set read_at = coalesce(read_at, now())
  where recipient_id = auth.uid()
    and sender_id = p_sender_id
    and read_at is null;
$$;

revoke all on function public.mark_messages_read(uuid) from public;
grant execute on function public.mark_messages_read(uuid) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Avatar images are public" on storage.objects;
create policy "Avatar images are public"
  on storage.objects for select
  using (bucket_id = 'avatars');

drop policy if exists "Users upload own avatar" on storage.objects;
create policy "Users upload own avatar"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users update own avatar" on storage.objects;
create policy "Users update own avatar"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users delete own avatar" on storage.objects;
create policy "Users delete own avatar"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

do $$
begin
  alter publication supabase_realtime add table public.app_messages;
exception
  when duplicate_object then null;
end $$;
