-- Run once in Supabase SQL Editor.
-- Stores SMS send attempts and provider responses for customer audit/history.

create table if not exists public.sms_logs (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.customers(id) on delete set null,
  user_id uuid references public.profiles(id) on delete set null,
  phone text not null,
  message text not null,
  provider text not null default 'interaktif_sms',
  provider_code text,
  provider_message_id text,
  provider_status integer,
  status text not null check (status in ('sent', 'failed')),
  error_message text,
  raw_response text,
  created_at timestamptz not null default now()
);

create index if not exists sms_logs_customer_created_idx
  on public.sms_logs (customer_id, created_at desc);

create index if not exists sms_logs_user_created_idx
  on public.sms_logs (user_id, created_at desc);

alter table public.sms_logs enable row level security;

drop policy if exists "sms_logs_select_by_role" on public.sms_logs;
create policy "sms_logs_select_by_role"
on public.sms_logs
for select
to authenticated
using (
  (select public.current_user_customer_role()) in ('boss', 'manager')
  or user_id = (select auth.uid())
);

revoke insert, update, delete on table public.sms_logs from authenticated;
grant select on table public.sms_logs to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'sms_logs'
  ) then
    alter publication supabase_realtime add table public.sms_logs;
  end if;
end
$$;

notify pgrst, 'reload schema';
